version: '3.7'
services:
  rating-redis:
    image: redis:latest
    container_name: rating-redis
    ports:
      - "6379"
    volumes:
      - redisdata:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  rating-api:
    # build: ../src/RatingApi
    image: serdarkalayci/rating-api
    container_name: rating-api
    ports:
      - "8090:80"
    environment:
      - REDIS_ADDR=rating-redis
volumes: 
    redisdata:
networks:
    default:
        name: rating_network
        driver: bridge